
version: '3.8'

services:
  djangoweb:
    build: .
    #image:    davy39/django-lxp:latest
    command: gunicorn djangoLxp.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./django-lxp:/home/djangolxp/django-lxp
      - static_volume:/home/djangolxp/django-lxp/staticfiles
      - media_volume:/home/djangolxp/django-lxp/mediafiles

      #user: 1000:1000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
    - djangodb
    networks:
      - traefik_network
  djangodb:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    networks:
      - traefik_network
  djangonginx:
    build: ./nginx
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles

    depends_on:
      - djangoweb
    # Utilisation sans traefik
    #ports:
    #  - 8080:80
    # Utilisation avec traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.django.loadbalancer.server.port=80"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
volumes:
  postgres_data:
  static_volume:
  media_volume:
