
version: '3.8'

services:
  web:
    image: davy39/django-lxp:latest
    volumes:
      - ./django-lxp:/django-lxp
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
    - db
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django
volumes:
  postgres_data:
