name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
          # Update submodule
      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Commit Submodule Update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule" && git push || echo "No changes to commit"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install poetry
        uses: Gr1N/setup-poetry@v7
      - run: poetry --version
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: davy39/django-lxp:latest
      - 
        name: Remote git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_SSH_IP }}
          username: ${{ secrets.DOCKER_SSH_USER }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          script: |
            cd docker-lxp
            git pull --recurse-submodules
            docker-compose -f docker-compose-prod.yml pull
            docker-compose -f docker-compose-prod.yml up -d
