name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: davy39/django-lxp:latest
      - 
        name: running docker info
        uses: ironhalik/docker-over-ssh-action@v1
        with:
          user: ${{ secrets.DOCKER_SSH_USER }}
          host: ${{ secrets.DOCKER_SSH_IP }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          script: |
            cd docker-lxp 
            git pull --recurse-submodules
            docker-compose pull  
            docker-compose up -f docker-compose-prod.yml -d
