name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: davy39/django-lxp:latest
      - 
        name: Deploy to Docker Host
        uses: wshihadeh/docker-deployment-action@v1
        with:
            remote_docker_host: ${{ secrets.DOCKER_SSH_USER }}@${{ DOCKER_SSH_IP }}
            ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
            ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
            deployment_mode: docker-compose
            copy_stack_file: true
            deploy_path: /var/lib/docker-deploy/
            stack_file_name: docker-compose-prod.yml
            keep_files: 5
            args: up -d
            docker_prune: 'false'
            pull_images_first: 'true'
